; PlatformIO Configuration for CollarNet ESP32-S3 SIM7670G

[platformio]
default_envs = esp32-s3-sim7670g
src_dir = .

[env:esp32-s3-sim7670g]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Configuración de memoria Flash 16MB y PSRAM Octal (OPI) 8MB
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv

build_src_filter = 
    +<alerts.cpp>
    +<camera_manager.cpp>
    +<camera_stream_server.cpp>
    +<geofence.cpp>
    +<gps_emulator.cpp>
    +<gps_manager.cpp>
    +<imu_manager.cpp>
    +<main.cpp>
    +<mqtt_manager.cpp>
    +<storage_manager.cpp>
    +<TinyGPS++.cpp>
    +<wifi_manager.cpp>

build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_speed = 115200
upload_speed = 921600
; upload_port = COM5
; monitor_port = COM5

lib_deps = 
    vshymanskyy/TinyGSM @ ^0.12.0
    knolleary/PubSubClient @ ^2.8.0
    bblanchon/ArduinoJson @ ^7.0.4
