name: agrogis_flutter
description: "AgroGIS - AplicaciÃ³n PWA y MÃ³vil para mediciÃ³n y registro topolÃ³gico de terrenos agrÃ­colas"
publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.2
  geolocator: ^13.0.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  http: ^1.2.1
  flutter_compass: ^0.8.1
  ota_update: ^7.1.0
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true